### ISSUE TITLE
undefined: runewidth.ZeroWidthJoiner

### ISSUE THREAD

**Issue by lebtech** [singalhimanshu/taskgo#13]
Fresh install of Go. Running go get returns this error each time.

> go get -u github.com/singalhimanshu/taskgo
# github.com/rivo/tview
..\go\src\github.com\rivo\tview\util.go:56:2: undefined: runewidth.ZeroWidthJoiner

**Comment by lebtech** [comment]
\> go get -u github.com/singalhimanshu/taskgo
\# github.com/rivo/tview
..\go\src\github.com\rivo\tview\util.go:56:2: undefined: runewidth.ZeroWidthJoiner

**Comment by singalhimanshu** [comment]
Thanks a lot for opening this issue. The problem was there was a release of [go-runewidth](https://github.com/mattn/go-runewidth) 0.10 which might have some breaking changes for tview. I have fixed this in 936664331e86e1ca8c4665cb4947b97cb0653dae and made a small change to the build instruction in 23368bfa66eaf04c122fd4f0b688f18595629df7 (I have just remove -u flag which uses the network to get the latest packages). Now you can try with `go get github.com/singalhimanshu/taskgo`. Please report me if you are still getting an error.
